version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Building the Java Maven application...
      - cd service
      - mvn clean package -DskipTests
      - zip -r ../service.zip *


artifacts:
  files:
    - service.zip
