version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Building the Java Maven application...
      - cd service
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Building the JAR artifact...
      - cp target/crud_ec2-0.0.1-SNAPSHOT.jar /codebuild/output/app.jar

artifacts:
  files:
    - /codebuild/output/app.jar
