version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

#  pre_build:
#    commands:
#      - echo Logging in to Amazon ECR...
#      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo "Running Infrastructure Update..."
      - npm install -g aws-cdk
      - cd code-pipeline-ebs
      - cdk deploy \
        -c appName=CRUD-EC2 \ 
        -c account=058486276453 \ 
        -c region=us-east-1 \
        -c githubOwner=durutheguru \ 
        -c githubRepo=cdk-patterns \
        -c githubBranch=main \
        -c db_username=duru \
        --all --verbose --require-approval never
      - cd ../service
      - echo "Building the Java Maven application..."
      - mvn clean package -DskipTests


artifacts:
  base-directory: service
  files:
    - '**/*'
